FROM python:3.9-slim

WORKDIR /app

# Postgres 연결용 라이브러리(libpq) 설치 필요
RUN apt-get update && apt-get install -y gcc libpq-dev && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# 실행
CMD ["python", "-m", "src.detector.signal_detector"]